stages:
  - build
  - deploy

build auto24-frontend:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
      - build
  tags:
    - auto24-frontend
  script:
    - npm install
    - npm run build

deploy auto24-frontend:
  stage: deploy
  tags:
    - auto24-frontend
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r build/. ~/front-deployment
