FROM node:12.16.3 as build

WORKDIR /app

COPY . /app/

# --silent, not going to log anything
RUN npm install --silent
RUN npm install react-scripts@latest -g --silent


RUN npm run build

FROM nginx:1.18.0

COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

