stages:
  - build
  - deploy

build heroes:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - auto24-frontend
  script:
    - npm install
    - npm run build

deploy heroes:
  stage: deploy
  tags:
    - auto24-frontend
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r build/. ~/front-deployment
